# Generated by Django 5.2.8 on 2025-11-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_membership_room_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_interaction',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
