# Generated by Django 5.2.8 on 2025-11-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_approve',
            field=models.BooleanField(default=False),
        ),
    ]
