# Generated by Django 5.2.8 on 2025-11-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0007_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMessage',
            fields=[
            ],
            options={
                'verbose_name': 'All Message',
                'verbose_name_plural': 'All Messages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chat.message',),
        ),
        migrations.CreateModel(
            name='UnapprovedMessage',
            fields=[
            ],
            options={
                'verbose_name': 'Unapproved Message',
                'verbose_name_plural': 'Unapproved Messages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chat.message',),
        ),
    ]
